
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlwlclyfclmonkdbzakp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsd2xjbHlmY2xtb25rZGJ6YWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NjIxNjcsImV4cCI6MjA1NjQzODE2N30._VzjloYJ7XRzOH8IcqtP-DNLrKBPFwW_ukKyF5ImSQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
